verina-dinata/rails-uni-review

- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- db/migrate/20220827060746_add_first_name_last_name_to_user.rb
- db/schema.rb
added migration to user. Please review
> User: add first name and last name

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_index.scss
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- db/schema.rb
did some css for sign-up page. Please review
> Sign-up css

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/views/pages/home.html.erb
Have created new class for home page card css. please review and merge
> Home page: added new class for card css

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/views/universities/index.html.erb
> Uni index page: css to card

- app/assets/stylesheets/components/_banner.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
Added css to the log in page. Some changes in sign up page. Please review. Thanks
> Add css to log in page

- app/views/universities/index.html.erb
> added fav button

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/controllers/pages_controller.rb
- app/controllers/universities_controller.rb
- app/javascript/controllers/autocomplete_controller.js
- app/javascript/controllers/index.js
- app/views/devise/registrations/new.html.erb
- app/views/pages/home.html.erb
- app/views/universities/_list.html.erb
- app/views/universities/index.html.erb
- config/routes.rb
Added search with autocomplete feature on home page. have still to do the css .please review. Thanks
> Added autocomplete search on home

- app/assets/stylesheets/components/_banner.scss
- app/javascript/controllers/autocomplete_controller.js
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/universities/_list.html.erb
> Search home

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_link.scss
- app/assets/stylesheets/components/_review.scss
- app/javascript/controllers/autocomplete_controller.js
- app/javascript/controllers/index.js
- app/javascript/controllers/insert_in_list_controller.js
- app/javascript/controllers/star_rating_controller.js
- app/views/pages/home.html.erb
- app/views/reviews/_form.html.erb
- app/views/universities/_list.html.erb
- app/views/universities/_review_form.html.erb
- app/views/universities/index.html.erb
- app/views/universities/show.html.erb
- package.json
- yarn.lock
- remove form for search bar on home page
- remove favorite button on uni index page
> Change radio button to star rating for review form

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_image.scss
- app/javascript/controllers/autocomplete_controller.js
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/universities/_list.html.erb
- app/views/universities/show.html.erb
> Home review2

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/views/pages/home.html.erb
- app/views/universities/index.html.erb
> Css changes

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_image.scss
- app/assets/stylesheets/config/_fonts.scss
- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
> Review carousel

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_image.scss
- app/views/pages/home.html.erb
> Change carousel style

- app/controllers/universities_controller.rb
- app/javascript/controllers/calendar_controller.js
- app/views/universities/index.html.erb
- app/views/universities/show.html.erb
Reverts verina-dinata/rails-uni-review#56
> Revert "Save to calendar function"

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_image.scss
- app/views/pages/home.html.erb
Please review. Carousel changed.
> Corousel css

- app/assets/stylesheets/components/_alert.scss
- app/views/layouts/application.html.erb
- app/views/universities/show.html.erb
- db/schema.rb
> Fix the alert css

- app/assets/stylesheets/components/_image.scss
- app/controllers/universities_controller.rb
- app/javascript/controllers/calendar_controller.js
- app/models/university.rb
- app/views/universities/index.html.erb
- app/views/universities/show.html.erb
- config/routes.rb
- db/schema.rb
Connect back-end for ratings, build internal ranking
> Finish rankings ratings

- app/assets/stylesheets/components/_card.scss
- app/views/favorites/index.html.erb
- app/views/universities/_favorite.html.erb
- app/views/universities/index.html.erb
> Add css to fav index page

- app/assets/stylesheets/components/_add_to_favourite.scss
- app/assets/stylesheets/components/_favcard.scss
- app/javascript/controllers/favorite_controller.js
- app/views/favorites/index.html.erb
- app/views/universities/_favorite.html.erb
- app/views/universities/index.html.erb
> completed wohooo

- app/assets/stylesheets/components/_image.scss
- db/seeds.rb
> Logo height resized

- db/seeds.rb
> Add review

- db/seeds.rb
> Add review to Singapore uni

- db/seeds.rb
> Change duplicate review

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_navbar.scss
> Clear comment out codes

- app/assets/stylesheets/components/_navbar.scss
- app/views/universities/show.html.erb
- db/seeds.rb
Add avatar to all users in seed file. This will increase the time it takes to run the seed file
> Add user avatar

- app/controllers/universities_controller.rb
- app/views/pages/home.html.erb
- app/views/universities/_star.html.erb
> Change rating star in home reviews

- db/seeds.rb
added new reviews for Australian universities
> added new reviews

- db/seeds.rb
> added missing commas

- app/views/pages/home.html.erb
> Add avatar to reviews on home page

- app/assets/stylesheets/components/_card.scss
- app/views/pages/home.html.erb
> Add new home cards

- app/views/pages/home.html.erb
> Remove old home cards

- app/assets/stylesheets/components/_card.scss
- app/views/pages/home.html.erb
> New pic for malaysia card

- app/views/universities/_university.html.erb
> Change total review in uni index page
